// <auto-generated />
namespace ProjectManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Tasks_Projects : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tasks_Projects));
        
        string IMigrationMetadata.Id
        {
            get { return "202002200712546_Tasks_Projects"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
